/**
 * One-time script: reads water_tree_export.txt and writes
 * supabase/migrations/20260502_seed_water_nodes.sql
 *
 * Run: npx ts-node scripts/parse-water-tree.ts
 */

import * as fs from 'fs'
import { fileURLToPath } from 'url'
import * as path from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const INPUT_FILE = 'd:\\km\\data\\water_tree.txt'
const OUTPUT_FILE = path.join(__dirname, '..', 'supabase', 'migrations', '20260502_seed_water_nodes.sql')

// Branch number → branches.code mapping
const BRANCH_MAP: Record<string, string> = {
  '29': 'NKS', '30': 'TTK', '31': 'LYW', '32': 'PYK',
  '33': 'CNT', '34': 'UTN', '35': 'KPP', '36': 'KNU',
  '37': 'TAK', '38': 'MSO', '39': 'SKT', '40': 'TSL',
  '41': 'SRR', '42': 'SWK', '43': 'SSN', '44': 'UTT',
  '45': 'PKM', '46': 'NKT', '47': 'PCT', '48': 'BML',
  '49': 'TPH', '50': 'PBC', '51': 'LOM', '52': 'CHN',
  '53': 'NNP', '54': 'VCB',
}

type NodeType = 'MM' | 'DMA' | 'SUB' | 'VD'

interface ParsedNode {
  branchCode: string
  nodeType: NodeType
  code: string
  nameTh: string | null
  status: 'จ่าย' | 'ส่ง' | 'รอปรับโซน' | null
  userCount: number | null
  depth: number
  parentCode: string | null
}

function esc(s: string | null): string {
  if (s === null) return 'NULL'
  return `'${s.replace(/'/g, "''")}'`
}

function parseNodeLine(
  line: string,
  branchCode: string,
  parentStack: (string | null)[]
): ParsedNode | null {
  // Must contain a recognized type marker
  const typeMatch = line.match(/\[(MM|DMA|SUB|VD|PRV)\]/)
  if (!typeMatch) return null

  // PRV is a pressure-reducing valve acting as DMA
  const nodeType: NodeType = typeMatch[1] === 'PRV' ? 'DMA' : (typeMatch[1] as NodeType)

  // Depth: position of '[' divided by 4
  const bracketPos = line.indexOf('[')
  const depth = Math.floor(bracketPos / 4)

  // Content after [TYPE]
  const afterBracket = line.slice(line.indexOf(']') + 1).trim()

  // Detect status
  let status: ParsedNode['status'] = null
  let statusIdx = -1
  const statusChars = ['◉', '→', '◈']
  for (const ch of statusChars) {
    const idx = afterBracket.indexOf(ch)
    if (idx !== -1 && (statusIdx === -1 || idx < statusIdx)) {
      statusIdx = idx
      if (ch === '◉') status = 'จ่าย'
      else if (ch === '→') status = 'ส่ง'
      else status = 'รอปรับโซน'
    }
  }

  const beforeStatus = (statusIdx >= 0 ? afterBracket.slice(0, statusIdx) : afterBracket).trim()
  const afterStatus = statusIdx >= 0 ? afterBracket.slice(statusIdx + 1).trim() : ''

  // Code: first non-space token before the status marker
  // Collapse internal spaces (handles "MM -05" → "MM-05")
  const rawCode = beforeStatus.split(/\s{2,}/)[0].trim().replace(/\s/g, '')
  const code = rawCode || 'UNKNOWN'

  // User count
  const ucMatch = afterStatus.match(/(\d[\d,]+)\s*ราย/)
  const userCount = ucMatch ? parseInt(ucMatch[1].replace(/,/g, ''), 10) : null

  // Name: text after user count, or text between code and status if no user count
  let nameTh: string | null = null
  if (ucMatch) {
    const rest = afterStatus.slice(afterStatus.indexOf(ucMatch[0]) + ucMatch[0].length).trim()
    if (rest) nameTh = rest
  }
  // Extra text between code and status (embedded name)
  const extraBeforeStatus = beforeStatus.slice(rawCode.length).trim()
  if (extraBeforeStatus) {
    nameTh = nameTh ? `${extraBeforeStatus} ${nameTh}` : extraBeforeStatus
  }
  // Name after status but before user count (rare: "→ ส่ง  — ชื่อ")
  if (!nameTh && afterStatus) {
    const cleanAfter = afterStatus.replace(/ส่ง|จ่าย|รอปรับโซน|—/g, '').trim()
    if (cleanAfter && !ucMatch) nameTh = cleanAfter || null
  }

  // Parent: use stack at depth-1
  const parentCode = depth > 0 ? (parentStack[depth - 1] ?? null) : null

  return { branchCode, nodeType, code, nameTh: nameTh || null, status, userCount, depth, parentCode }
}

function generateSql(nodes: ParsedNode[]): string {
  const mmNodes = nodes.filter((n) => n.depth === 0)
  const childNodes = nodes.filter((n) => n.depth > 0)

  const lines: string[] = [
    '-- Seed: water distribution nodes (generated by scripts/parse-water-tree.ts)',
    '-- Pass 1: MM nodes (top-level, no parent)',
    '',
  ]

  for (const n of mmNodes) {
    lines.push(
      `INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)` +
        `\nSELECT id, '${n.nodeType}', ${esc(n.code)}, ${esc(n.nameTh)}, ${esc(n.status)}, ${n.userCount ?? 'NULL'}` +
        `\nFROM branches WHERE code = '${n.branchCode}'` +
        `\nON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;`
    )
  }

  lines.push('', '-- Pass 2: DMA/VD/SUB children', '')

  for (const n of childNodes) {
    if (!n.parentCode) {
      lines.push(`-- WARN: no parent for ${n.branchCode}/${n.code}, skipping`)
      continue
    }
    lines.push(
      `INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)` +
        `\nSELECT b.id, '${n.nodeType}', ${esc(n.code)}, ${esc(n.nameTh)}, p.id, ${esc(n.status)}, ${n.userCount ?? 'NULL'}` +
        `\nFROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = ${esc(n.parentCode)}` +
        `\nWHERE b.code = '${n.branchCode}'` +
        `\nON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;`
    )
  }

  return lines.join('\n')
}

function main() {
  const raw = fs.readFileSync(INPUT_FILE, 'utf8')
  const lines = raw.split('\n')

  const nodes: ParsedNode[] = []
  let currentBranchCode = ''
  const parentStack: (string | null)[] = [null, null, null, null]

  for (const rawLine of lines) {
    // Strip box-drawing chars from line start for detection
    const stripped = rawLine.replace(/[╔╠╣╗╚╝═║]/g, '').trim()

    // Branch header
    const branchMatch = rawLine.match(/▶\s*\[(\d+)\]/)
    if (branchMatch) {
      currentBranchCode = BRANCH_MAP[branchMatch[1]] ?? ''
      parentStack.fill(null)
      continue
    }

    if (!currentBranchCode) continue

    const node = parseNodeLine(rawLine, currentBranchCode, parentStack)
    if (!node) continue

    nodes.push(node)

    // Update parent stack
    parentStack[node.depth] = node.code
    for (let i = node.depth + 1; i < parentStack.length; i++) parentStack[i] = null
  }

  const sql = generateSql(nodes)
  fs.writeFileSync(OUTPUT_FILE, sql, 'utf8')
  console.log(`Written ${nodes.length} nodes to ${OUTPUT_FILE}`)

  // Summary
  const byType = nodes.reduce((acc, n) => {
    acc[n.nodeType] = (acc[n.nodeType] ?? 0) + 1
    return acc
  }, {} as Record<string, number>)
  console.log('Node counts:', byType)
}

main()
