-- Seed: water distribution nodes (generated by scripts/parse-water-tree.ts)
-- Pass 1: MM nodes (top-level, no parent)

INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'หน่วยบริการเก้าเลี้ยว', 'จ่าย', 4849
FROM branches WHERE code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'สถานีผลิตน้ำทับกฤช', 'จ่าย', 1895
FROM branches WHERE code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'สถานีผลิตน้ำโกรกพระ', 'จ่าย', 2336
FROM branches WHERE code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'หนองกระโดน', 'จ่าย', 1073
FROM branches WHERE code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'แม่ข่ายท่าตะโก', 'ส่ง', NULL
FROM branches WHERE code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'ข้างใน น.ไพศาลี', 'จ่าย', 3466
FROM branches WHERE code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'ข้างใน น.มะเกลือหวาน', 'จ่าย', 2444
FROM branches WHERE code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'หน่วยบริการหนองบัว', 'จ่าย', 2592
FROM branches WHERE code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05', 'มะเกลือหวาน ไพศาลี', 'ส่ง', NULL
FROM branches WHERE code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สถานีผลิตน้ำบึงหล่ม', 'จ่าย', 6903
FROM branches WHERE code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'หน่วยฯบรรพตพิสัย', 'จ่าย', 1432
FROM branches WHERE code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'หนองกระโดนลาดยาว', 'รอปรับโซน', NULL
FROM branches WHERE code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-01', 'แม่ข่ายพยุหะคีรี(เนินมะกอก , ม่วงหัก)', 'จ่าย', 2388
FROM branches WHERE code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-02', 'แม่ข่ายพยุหะคีรี (#สระทะเล #ย่านมัทรี)', 'จ่าย', 2212
FROM branches WHERE code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-03', 'หน่วยบริการหาดเหนือ(พยุหะ ท่าน้ำอ้อย ม่วงหัก มโนรมย์)', 'จ่าย', 4887
FROM branches WHERE code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-06', 'หน่วยบริการน้ำเขาทอง(#เขาทอง)', 'จ่าย', 2266
FROM branches WHERE code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-07', 'หน่วยบริการน้ำเขาทอง(#ยางตาล #โตโยต้า)', 'จ่าย', 173
FROM branches WHERE code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-08', 'ยางตาล(#กลางแดด#เขาเขียว)', 'จ่าย', 557
FROM branches WHERE code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-09', 'บ้านหัวงิ้ว', 'รอปรับโซน', NULL
FROM branches WHERE code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สำนักงานประปาชัยนาท', 'ส่ง', NULL
FROM branches WHERE code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'หน่วยบริการหันคา', 'จ่าย', 3902
FROM branches WHERE code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'VSD จ่ายสวนนกชัยนาท (DMA06)', 'จ่าย', 640
FROM branches WHERE code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สำนักงานประปาหนองฉาง', 'ส่ง', NULL
FROM branches WHERE code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'หน่วยบริการหนองขาหย่าง', 'จ่าย', 4441
FROM branches WHERE code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'หน่วยบริการสว่างอารมณ์', 'จ่าย', 842
FROM branches WHERE code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'หน่วยบริการน้ำพุ-เนินพะยอม', 'จ่าย', 1023
FROM branches WHERE code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05', 'หน่วยฯลานสัก', 'จ่าย', 671
FROM branches WHERE code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-06', 'หน่วยบริการทัพทัน', 'จ่าย', 2346
FROM branches WHERE code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'จ่ายไปศูนย์ราชการ 400มม', 'จ่าย', 3578
FROM branches WHERE code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'จ่ายไปพรานกระต่าย 100 มม', 'จ่าย', 3345
FROM branches WHERE code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'สถานีผลิตน้ำหนองปลิง', 'จ่าย', 14479
FROM branches WHERE code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05', 'สถานีผลิตน้ำหนองน้ำขาว', 'จ่าย', 1694
FROM branches WHERE code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-06', 'จ่ายไตรตรึงษ์', 'จ่าย', 938
FROM branches WHERE code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-07', 'หน่วยบริการลานกระบือ', 'จ่าย', 1605
FROM branches WHERE code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-08', 'หน่วยบริการคลองลาน', 'จ่าย', 1999
FROM branches WHERE code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'มาตรวัดน้ำหลักแพลนขาณุ', 'ส่ง', NULL
FROM branches WHERE code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'มาตรวัดน้ำหลักแพลนท่ามะเขือ', 'ส่ง', NULL
FROM branches WHERE code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'มาตรวัดน้ำหลักแพลนขาณุฯ', 'ส่ง', NULL
FROM branches WHERE code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'ใต้ถังสูง-โซนต่ำ', 'ส่ง', NULL
FROM branches WHERE code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'โรงกรองน้ำ กปภ.สาขาตาก-โซนสูง', 'ส่ง', NULL
FROM branches WHERE code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'น.บ้านตาก', 'จ่าย', 3139
FROM branches WHERE code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'น.สามเงา', 'จ่าย', 1655
FROM branches WHERE code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05', 'น.วังเจ้า', 'จ่าย', 2201
FROM branches WHERE code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สถานีแม่ข่าย', 'จ่าย', 3130
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'สถานีแม่ข่าย / DMA-04-เอเซียขวา', 'จ่าย', 2016
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'สถานีแม่ข่าย', 'ส่ง', NULL
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'สถานีแม่ข่าย', 'ส่ง', NULL
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05', 'สถานีราชภัฏ', 'ส่ง', NULL
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-06', 'สถานีพระธาตุผาแดง', 'จ่าย', 7533
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-08', 'สถานีห้วยม่วง', 'รอปรับโซน', NULL
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-09', 'สถานีแม่ระมาด', 'จ่าย', 2005
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-10', 'สถานีแม่ระมาด', 'จ่าย', 991
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-11', 'พบพระ', 'จ่าย', 94
FROM branches WHERE code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สถานีผลิตน้ำปากแคว พื้นที่จ่ายน้ำเทศบาลเมืองสุโขทัย', 'จ่าย', 4517
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'สถานีผลิตน้ำปากแคว พื้นที่จ่ายน้ำโรงเรียนอุดมดรุณี', 'จ่าย', 1115
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'สถานีผลิตน้ำปากแคว พื้นที่จ่ายน้ำ บ้านบางคลอง', 'จ่าย', 430
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05', 'สถานีผลิดน้ำทุ่งทะเลหลวง พื้นที่จ่ายน้ำ ต.บ้านกล้วย', 'จ่าย', 4137
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-08', 'หน่วยบริการกงไกรลาศ', 'จ่าย', 1539
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-09', 'หน่วยบริการบ้านสวน', 'จ่าย', 2485
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-11', 'หน่วยบริการทุ่งหลวง-คีรีมาศ', 'จ่าย', 2565
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-12', 'หน่วยบริการเมืองเก่า', 'จ่าย', 3329
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-14', 'หน่วยบริการบ้านด่านลานหอย', 'จ่าย', 2084
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-15', 'ถังน้ำใสเขาค่ายจ่ายหน่วยบริการบ้านด่านลานหอย', 'จ่าย', 533
FROM branches WHERE code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'บ้านกลางดง', 'จ่าย', 1227
FROM branches WHERE code = 'TSL'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'เทศบาล ต.ทุ่งเสลี่ยม', 'จ่าย', 2360
FROM branches WHERE code = 'TSL'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-01', 'ต.คลองตาล', 'จ่าย', 1696
FROM branches WHERE code = 'SRR'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-02', 'ต.เกาะตาเลี้ยง', 'จ่าย', 1495
FROM branches WHERE code = 'SRR'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-03', 'ต.วัดเกาะ', 'จ่าย', 815
FROM branches WHERE code = 'SRR'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-01', 'สำนักงานประปา', 'จ่าย', 7770
FROM branches WHERE code = 'SWK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-04', 'น.ศรีนคร', 'จ่าย', 1152
FROM branches WHERE code = 'SWK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สถานีผลิตน้ำห้วยแม่สูง', 'จ่าย', 5088
FROM branches WHERE code = 'SSN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'น.ท่าชัย', 'จ่าย', 3607
FROM branches WHERE code = 'SSN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01ท่อจ่ายน้ำริด400มม', 'มม', 'ส่ง', NULL
FROM branches WHERE code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02สถานีตรอน', 'น', 'ส่ง', NULL
FROM branches WHERE code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03ท่อจ่ายปากฝาง', 'ง', 'ส่ง', NULL
FROM branches WHERE code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'หน่วยบริการหัวรอ(DMA01)', 'จ่าย', 10206
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'หน่วยบริการบางระกำ(DMA08)', 'จ่าย', 1668
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'หน่วยบริการวังทอง(DMA11)', 'จ่าย', 1954
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05', 'หน่วยบริการสมอแข(DMA13)', 'จ่าย', 3113
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-06', 'หน่วยบริการบางกระทุ่ม(DMA15)', 'จ่าย', 1127
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-07', 'หน่วยบริการเนินกุ่ม(DMA16)', 'จ่าย', 776
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-08', 'หน่วยบริการพรหมพิราม(DMA17)', 'จ่าย', 2985
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-09', 'แม่ข่ายสมอแคลง(DMA18)', 'จ่าย', 1248
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-10', 'หน่วยบริการบ้านใหม่(DMA19)', 'จ่าย', 730
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-11', 'หน่วยบริการเนินมะปราง(DMA22)', 'จ่าย', 690
FROM branches WHERE code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-01', 'สถานีผลิตน้ำหนองกะท้าว (ด้านซ้าย)', 'จ่าย', 1298
FROM branches WHERE code = 'NKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-02', 'สถานีผลิตน้ำหนองกะท้าว (ด้านขวา)', 'จ่าย', 172
FROM branches WHERE code = 'NKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-05', 'สถานีผลิตน้ำชาติตระการ', 'จ่าย', 2347
FROM branches WHERE code = 'NKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'ม.พิจิตร (เมืองพิจิตร)', 'ส่ง', NULL
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'น.สากเหล็ก (จ่ายสากเหล็ก)', 'จ่าย', 1523
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'น.สากเหล็ก (จ่ายเนินกุ่ม-ป่ามะคาบ)', 'จ่าย', 722
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'น.วังกรด (จ่ายวังกรด)', 'จ่าย', 2884
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-06', 'น.หัวดง (จ่ายหัวดง)', 'จ่าย', 1566
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-07', 'น.วังทรายพูน (่จ่ายวังทรายพูน-หนองพระ)', 'จ่าย', 866
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-09', 'น.โคกสลุด', 'จ่าย', 3963
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-10', 'ม.พิจิตร (จ่ายท่าฬ่อ)', 'จ่าย', 1081
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-13', 'น.วังทรายพูน (จ่ายวังทรายพูน)', 'จ่าย', 2208
FROM branches WHERE code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สำนักงานประปา', 'ส่ง', NULL
FROM branches WHERE code = 'BML'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'หน่วยบริการบางใผ่', 'จ่าย', 675
FROM branches WHERE code = 'BML'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'หน่วยบริการโพทะเล', 'จ่าย', 1027
FROM branches WHERE code = 'BML'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สำนักงานประปา 500 mm.', 'ส่ง', NULL
FROM branches WHERE code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-06', 'ลงถังน้ำใส สถานีน้ำ วังหลุม', 'ส่ง', NULL
FROM branches WHERE code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02-TK', 'น.ทับคล้อ 300 mm.', 'ส่ง', NULL
FROM branches WHERE code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'สถานีผลิตน้ำหนองนารี', 'ส่ง', NULL
FROM branches WHERE code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'สถานีผลิตน้ำป่าแดง', 'ส่ง', NULL
FROM branches WHERE code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03สถานีผลิตน้ำป่าแดง(DMA-04-ป่าแดง)', 'ง)', 'ส่ง', NULL
FROM branches WHERE code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'DMA-01', 'บ้านติ้ว,บ้านโสก,บ้านวังรู,บ้านสักหลง (มาตรหลัก MM-01)', 'จ่าย', 14608
FROM branches WHERE code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'แม่ข่าย (สำนักงานประปา )', 'จ่าย', 3407
FROM branches WHERE code = 'CHN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'หน่วยบริการวังโป่ง', 'จ่าย', 1212
FROM branches WHERE code = 'CHN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'แม่ข่ายหนองไผ่ (DMA-01)', 'จ่าย', 1301
FROM branches WHERE code = 'NNP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'ฝั่งตลาดแสงอาทิตย์ (DMA-02)', 'จ่าย', 3030
FROM branches WHERE code = 'NNP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-03', 'สถานี รับ-ส่งน้ำบ้านโภชน์ (DMA-03)', 'จ่าย', 417
FROM branches WHERE code = 'NNP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-04', 'หน่วยบริการบึงสามพัน (DMA-04)', 'จ่าย', 2061
FROM branches WHERE code = 'NNP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-01', 'เมืองวิเชียร-สระประดู่ ซ.4', 'จ่าย', 4766
FROM branches WHERE code = 'VCB'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-02', 'ขึ้นถังสูงสำนักงาน', 'ส่ง', NULL
FROM branches WHERE code = 'VCB'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-05-ศรีเทพฝั่งตลาด-โคกสะอาดฝั่งโรงเรียน', 'ียน', 'จ่าย', 2482
FROM branches WHERE code = 'VCB'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, status, user_count)
SELECT id, 'MM', 'MM-07', 'โคกสะอาดฝั่งอนามัย', 'จ่าย', 723
FROM branches WHERE code = 'VCB'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, user_count = EXCLUDED.user_count;

-- Pass 2: DMA/VD/SUB children

INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-MM-01', NULL, p.id, 'จ่าย', 1152
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'หน้าไปรษณีย์เก้าเลี้ยว', p.id, 'จ่าย', 1617
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'หน้าอำเภอเก้าเลี้ยว', p.id, 'จ่าย', 806
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-04', 'หนองเต่า', p.id, 'จ่าย', 1273
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03'
WHERE b.code = 'NKS'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'ที่ว่าการอำเภอท่าตะโก', p.id, 'จ่าย', 1256
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'วัดหัวถนน', p.id, 'จ่าย', 1234
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'วัดเขาน้อย', p.id, 'จ่าย', 489
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'วัดเขาล้อ', p.id, 'จ่าย', 974
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'ตลาดท่าตะโก', p.id, 'จ่าย', 1754
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TTK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-MM-01', NULL, p.id, 'จ่าย', 25
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'ที่ว่าการอำเภอ', p.id, 'จ่าย', 1719
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-03', 'ไปรษณีย์', p.id, 'จ่าย', 1673
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'ตลาดลาดยาว', p.id, 'จ่าย', 1087
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-04', 'บ.หนองนมวัว', p.id, 'จ่าย', 2399
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'LYW'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-03', NULL, p.id, 'จ่าย', 3487
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03'
WHERE b.code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'ท่าแร่(#ท่าน้ำอ้อย)', p.id, 'จ่าย', 1193
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03'
WHERE b.code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'โรงกลึง(การไฟฟ้า-สะพานอุทัย)', p.id, 'จ่าย', 207
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03'
WHERE b.code = 'PYK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'ตรงข้ามโรงกรองน้ำชัยนาท', p.id, 'จ่าย', 1640
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'หน้าโรงกรองน้ำชัยนาท', p.id, 'จ่าย', 5990
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-02', NULL, p.id, 'จ่าย', 3404
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-03', 'ตรงข้ามศาลากลางจังหวัดขัยนาท', p.id, 'จ่าย', 2583
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'ธรรมมูล', p.id, 'จ่าย', 143
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'ปากซอยเทศบาล12', p.id, 'จ่าย', 1940
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'CNT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'ทุ่งพง', p.id, 'จ่าย', 958
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'หนองสรวง', p.id, 'จ่าย', 521
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'หน้าอำเภอหนองฉาง', p.id, 'จ่าย', 1858
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'หลังตลาด', p.id, 'จ่าย', 504
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'UTN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'KP09-DMA-09', 'จ่ายชากังราว', p.id, 'จ่าย', 3080
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-MM-03', NULL, p.id, 'จ่าย', 1084
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'KP07-DMA-07', 'จ่ายคลองบางทวน', p.id, 'จ่าย', 962
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'KP08-DMA-08', 'จ่ายราชดำเนินซ้าย', p.id, 'จ่าย', 7115
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-08', NULL, p.id, 'จ่าย', 3398
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'KP11-DMA-11', 'จ่ายเจริญสุขล่าง', p.id, 'จ่าย', 1828
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'KP12-DMA-12', 'จ่ายราชดำเนินขวา', p.id, 'จ่าย', 1886
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'KP10-DMA-10', 'จ่ายเจริญสุขบน', p.id, 'จ่าย', 1604
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'MM-04', 'สถานีจ่ายน้ำนครชุม', p.id, 'จ่าย', 4945
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-05'
WHERE b.code = 'KPP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'PRV-DMA-01-ในแพลนขาณุ', NULL, p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-01', 'จ่ายน้ำฝั่งขวาไปสลกบาตร', p.id, 'จ่าย', 2082
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'PRV-DMA-01-ในแพลนขาณุ'
WHERE b.code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'จ่ายน้ำฝั่งซ่ายไปสลกบาตร', p.id, 'จ่าย', 1409
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'จ่ายน้ำไปตำบลท่าพุทรา', p.id, 'จ่าย', 796
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'จ่ายน้ำไปตำบลท่ามะเขือ', p.id, 'จ่าย', 1380
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-06', NULL, p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'จ่ายน้ำไปขาณุวรลักษบุรี', p.id, 'จ่าย', 921
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'KNU'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'หนองหลวง หัวเดียด ไม้งาม', p.id, 'จ่าย', 3472
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-09', 'ป่ามะม่วง หนองบัวเหนือ', p.id, 'จ่าย', 1697
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'มหาดไทยบำรุง ฝั่งตะวันตก', p.id, 'จ่าย', 1526
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-01', 'คลองห้วยทราย หนองบัวใต้', p.id, 'จ่าย', 1333
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-04'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-08', 'ท่าแค น้ำโจน วังหิน', p.id, 'จ่าย', 1573
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'มหาดไทยบำรุง ฝั่งตะวันออก', p.id, 'จ่าย', 2372
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'บ้านแพะ เทคโน หนองกระโห้', p.id, 'จ่าย', 2339
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-06', 'น้ำรึมฝั่งขวา', p.id, 'จ่าย', 4835
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-07', 'ลานขวาง พหลโยธินขาออก', p.id, 'จ่าย', 2658
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'TAK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'อินทรคีรี', p.id, 'จ่าย', 3130
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'ริมเมย', p.id, 'จ่าย', 1130
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'บัวคุณ', p.id, 'จ่าย', 1830
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'เอเซียซ้าย', p.id, 'จ่าย', 1651
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-06', 'แม่ปะ', p.id, 'จ่าย', 6022
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-07', 'สะพานมิตรภาพ 2', p.id, 'รอปรับโซน', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-04'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-08', 'ราชภัฏ', p.id, 'จ่าย', 379
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-05'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-MM-06', NULL, p.id, 'จ่าย', 5579
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-06'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-10', 'แม่กุ', p.id, 'รอปรับโซน', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-06'
WHERE b.code = 'MSO'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'MM-06', 'ถนนประเวชนคร', p.id, 'จ่าย', 1537
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-05'
WHERE b.code = 'SKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'บ้านวังธาร', p.id, 'จ่าย', 1706
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TSL'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-02', NULL, p.id, 'จ่าย', 1973
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'TSL'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'บ้านคลองสำราญ', p.id, 'จ่าย', 383
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'TSL'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-01', NULL, p.id, 'จ่าย', 3558
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'SWK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'สามแยกประปาเก่า', p.id, 'จ่าย', 4207
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'SWK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-02', NULL, p.id, 'จ่าย', 1848
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'SWK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-03', 'ข้างวัดสว่างอารมณ์ฯ', p.id, 'จ่าย', 2356
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'SWK'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-MM-01', NULL, p.id, 'จ่าย', 954
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'SSN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'ข้าง รพ.ศรีสัชนาลัย', p.id, 'จ่าย', 400
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'SSN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'ท่าสนามกีฬาป่างิ้ว', p.id, 'จ่าย', 1092
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'SSN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'ฝั่งบ้านพัก อส.', p.id, 'จ่าย', 952
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'SSN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'ฝั่งบ้านพักนายอำเภอ', p.id, 'จ่าย', 1690
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'SSN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'น้ำริด', p.id, 'จ่าย', 1036
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01ท่อจ่ายน้ำริด400มม'
WHERE b.code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'บัวหลวง', p.id, 'จ่าย', 711
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01ท่อจ่ายน้ำริด400มม'
WHERE b.code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-06', 'ชายเขา', p.id, 'จ่าย', 333
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01ท่อจ่ายน้ำริด400มม'
WHERE b.code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'วังสีสูบ', p.id, 'จ่าย', 1040
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03ท่อจ่ายปากฝาง'
WHERE b.code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'ปากฝาง', p.id, 'จ่าย', 1032
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03ท่อจ่ายปากฝาง'
WHERE b.code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'คุ้งตะเภา', p.id, 'จ่าย', 805
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03ท่อจ่ายปากฝาง'
WHERE b.code = 'UTT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'พื้นที่จ่ายน้ำหัวรอ', p.id, 'จ่าย', 3618
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-03', 'พื้นที่จ่ายน้ำบ้านเต็งหนาม', p.id, 'จ่าย', 1736
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-04', 'พื้นที่จ่ายน้ำพลายชุมพล', p.id, 'จ่าย', 923
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'พื้นที่น้ำแยกไทยแอร์โร่', p.id, 'รอปรับโซน', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'MM-02', 'หน่วยบริการบ้านกร่าง(DMA06)', p.id, 'จ่าย', 1199
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-07', 'พื้นที่จ่ายน้ำเซ็นทรัล', p.id, 'จ่าย', 388
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-09', 'พื้นที่จ่ายน้ำปลัคแรด', p.id, 'จ่าย', 1182
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-10', 'พื้นที่จ่ายน้ำ ม.นเรศวร', p.id, 'จ่าย', 2746
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-12', 'พื้นที่จ่ายน้ำตลาดวังทอง', p.id, 'จ่าย', 1612
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-04'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-21', 'ค่ายเอกาทศรส', p.id, 'จ่าย', 3057
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-05'
WHERE b.code = 'PKM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'หน้าโรงพยาบาลสมเด็จพระยุพราชนครไทย', p.id, 'จ่าย', 2535
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'NKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'หน้าศูนย์รถ TOYOTA', p.id, 'จ่าย', 968
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02'
WHERE b.code = 'NKT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'หน้าสำนักงานประปา', p.id, 'จ่าย', 998
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-10ใกล้สะพานข้ามแม่น้ำฝั่งซ้าย', 'าย', p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-11ใกล้สะพานข้ามแม่น้ำฝั่งขวา', 'วา', p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02หน้าคูโบต้า', 'า', p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-04', 'หน้าเทคนิค', p.id, 'จ่าย', 1560
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-02หน้าคูโบต้า'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-06', 'ใกล้วัดโรงช้าง', p.id, 'จ่าย', 1111
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-04'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03ตรงข้ามโชว์รูมนิสสัน', 'น', p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-05', 'ข้างวีอาร์ พลาซ่า', p.id, 'จ่าย', 1425
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03ตรงข้ามโชว์รูมนิสสัน'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-07', 'ตรงข้ามขนส่ง', p.id, 'จ่าย', 2626
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-09', 'สี่แยกนครแพร่', p.id, 'จ่าย', 1219
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-08', 'ตรงข้ามอบจ.พิจิตร', p.id, 'จ่าย', 1027
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-09'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-12', 'ป่ามะคาบ', p.id, 'จ่าย', 1447
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'PCT'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'เทศบาลเมืองบางมูลนาก', p.id, 'จ่าย', 2880
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'BML'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'เทศบาล ต.หอไกร', p.id, 'จ่าย', 1504
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'BML'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'หมู่4 ต.หอไกร', p.id, 'จ่าย', 718
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'BML'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'จ่ายข้ามทางรถไฟ-หนุมาน', p.id, 'จ่าย', 4168
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'จ่ายตลาด-ฝั่งข้ามแม่น้ำ', p.id, 'จ่าย', 2383
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'จ่ายป่าแดง', p.id, 'จ่าย', 631
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'จ่ายงิ้งราย', p.id, 'จ่าย', 501
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'จ่ายหมู่บ้านเขารวก', p.id, 'จ่าย', 180
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-06'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-06', 'จ่ายตำบลวังหลุม', p.id, 'จ่าย', 939
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-06'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01-TK', 'จ่ายทับคล้อ 150 mm', p.id, 'จ่าย', 1719
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02-TK'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02-TK', 'จ่ายเขาทราย', p.id, 'จ่าย', 1295
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02-TK'
WHERE b.code = 'TPH'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'หนองนารี', p.id, 'จ่าย', 1668
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'ศูนย์ราชการเพชรบูรณ์', p.id, 'จ่าย', 3097
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'โรงพยาบาลเพชรบูรณ์', p.id, 'จ่าย', 1243
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05', 'ป่าเลา', p.id, 'จ่าย', 1595
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-06', 'สะเดียง', p.id, 'จ่าย', 2079
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-07', 'หน้าค่ายพ่อขุนผาเมือง', p.id, 'จ่าย', 3179
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-08', 'วัดมหาธาตุ/ศาลหลักเมือง', p.id, 'จ่าย', 1034
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-09', 'สระกลางเมือง', p.id, 'จ่าย', 3051
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-10', 'หมู่บ้านการเคหะ', p.id, 'จ่าย', 2270
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'PBC'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-01', NULL, p.id, 'จ่าย', 520
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'บ้านบึง,รพ.หล่มสัก,กฟภ.หล่มสัก', p.id, 'จ่าย', 2019
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'ตลาดหล่มสัก,Big C,น้ำพุงใต้', p.id, 'จ่าย', 5732
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-03', NULL, p.id, 'จ่าย', 4308
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-05', 'เทศบาลตำบลตาลเดี่ยว,บ้านท่าช้าง', p.id, 'จ่าย', 1414
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-04', 'พ่อขุนผาเมืองและตำบลหนองไขว่', p.id, 'จ่าย', 402
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-06', 'สามแยกสักหลง ถึง อบต.นาแซง', p.id, 'จ่าย', 3730
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-DMA-06', NULL, p.id, 'จ่าย', 197
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-06'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-07', 'ตลาดหล่มเก่า,วังบาล,บ้านเนิน,หนองสว่าง', p.id, 'จ่าย', 3532
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-06'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-08บ้านสักหลงม.8ต.สักหลง', 'หลง', p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-09บ้านห้วยไร่', '่', p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-01'
WHERE b.code = 'LOM'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'VD', 'VD-MM-01', NULL, p.id, 'จ่าย', 78
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'CHN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-01', 'ฝั่งโรงเรียน', p.id, 'จ่าย', 293
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'CHN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'ฝั่งประปา', p.id, 'จ่าย', 3035
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-01'
WHERE b.code = 'CHN'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-05สถานีจ่ายน้ำบ้านโภชน์', '์', p.id, 'ส่ง', NULL
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-03'
WHERE b.code = 'NNP'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-02', 'สามแยกวิเชียร-ดงเข็ม', p.id, 'จ่าย', 511
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'VCB'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'DMA', 'DMA-03', 'พุเตย-พุขาม', p.id, 'จ่าย', 683
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'MM-02'
WHERE b.code = 'VCB'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;
INSERT INTO water_nodes (branch_id, node_type, code, name_th, parent_id, status, user_count)
SELECT b.id, 'SUB', 'DMA-04', 'พุเตย ฝั่งเซเว้น', p.id, 'จ่าย', 730
FROM branches b JOIN water_nodes p ON p.branch_id = b.id AND p.code = 'DMA-03'
WHERE b.code = 'VCB'
ON CONFLICT (branch_id, code) DO UPDATE SET name_th = EXCLUDED.name_th, parent_id = EXCLUDED.parent_id, user_count = EXCLUDED.user_count;